export const state = {
  tab: "hangar",
  selected: { type: "chassis" },
  nextId: 3,
  scale: 0.4,
  panX: 20,
  panY: 20,
  hangarScale: 1,
  hangarPanX: 20,
  hangarPanY: 20,
  x: 420,
  y: 720,
  heading: 0,
  startX: 420,
  startY: 720,
  startH: 0,
  poseLocked: false,
  running: false,
  length: 200,
  width: 180,
  W: 130,
  parts: [
    { id: 1, kind: "clamp", x: 0, y: 44, face: "front", w: 56, d: 72 },
    { id: 2, kind: "gripper", x: 0, y: -52, face: "back", w: 56, d: 64 },
  ],
  unused: "yellow",
  useUnused: false,
  slots: ["red", "green", "blue", "black"],
  arts: [],
  keepArts: true,
  sweepBatch: false,
};

export const input = {
  spaceDown: false,
  pan: null,
  hangarPan: null,
  hangarDrag: null,
  paletteDrag: null,
  skipPartClick: false,
  liveRaf: 0,
  fieldDrag: null,
  artDrag: null,
};
