export const session = {
  STORE: "artefact-program-v1",
  COLORS: {
    motion: "#4c97ff",
    control: "#ffab19",
    ops: "#59c059",
    vars: "#ff8c1a",
    lists: "#cf63cf",
    field: "#0fbd8c",
  },
  nid: 1,
  ws: { vars: ["n", "i", "held", "unused", "gx", "gy"], lists: ["colors"], script: [] },
  source: "blocks",
  selected: null,
  drag: null,
  runTok: null,
  instant: false,
  speed: 10,
  simTimeMs: 0,
  batch: false,
};
